"""add community posts, comments, and votes

Revision ID: 98bb4054a270
Revises: e7a2c4b8f105
Create Date: 2026-08-18 20:13:02.035255

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '98bb4054a270'
down_revision = 'e7a2c4b8f105'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('community_posts',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=200), nullable=False),
    sa.Column('body', sa.Text(), nullable=False),
    sa.Column('post_type', sa.String(length=20), nullable=False),
    sa.Column('tool_slug', sa.String(length=120), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('is_hidden', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('community_posts', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_community_posts_created_at'), ['created_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_community_posts_tool_slug'), ['tool_slug'], unique=False)
        batch_op.create_index(batch_op.f('ix_community_posts_user_id'), ['user_id'], unique=False)

    op.create_table('community_comments',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('post_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('body', sa.String(length=1000), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('is_hidden', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['post_id'], ['community_posts.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('community_comments', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_community_comments_created_at'), ['created_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_community_comments_post_id'), ['post_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_community_comments_user_id'), ['user_id'], unique=False)

    op.create_table('post_votes',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('post_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('vote_type', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.CheckConstraint('vote_type = 1 OR vote_type = -1', name='ck_post_vote_type'),
    sa.ForeignKeyConstraint(['post_id'], ['community_posts.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('post_id', 'user_id', name='uq_post_user_vote')
    )
    with op.batch_alter_table('post_votes', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_post_votes_post_id'), ['post_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_post_votes_user_id'), ['user_id'], unique=False)

    op.create_table('comment_votes',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('comment_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('vote_type', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.CheckConstraint('vote_type = 1 OR vote_type = -1', name='ck_comment_vote_type'),
    sa.ForeignKeyConstraint(['comment_id'], ['community_comments.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('comment_id', 'user_id', name='uq_comment_user_vote')
    )
    with op.batch_alter_table('comment_votes', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_comment_votes_comment_id'), ['comment_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_comment_votes_user_id'), ['user_id'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('comment_votes', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_comment_votes_user_id'))
        batch_op.drop_index(batch_op.f('ix_comment_votes_comment_id'))

    op.drop_table('comment_votes')
    with op.batch_alter_table('post_votes', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_post_votes_user_id'))
        batch_op.drop_index(batch_op.f('ix_post_votes_post_id'))

    op.drop_table('post_votes')
    with op.batch_alter_table('community_comments', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_community_comments_user_id'))
        batch_op.drop_index(batch_op.f('ix_community_comments_post_id'))
        batch_op.drop_index(batch_op.f('ix_community_comments_created_at'))

    op.drop_table('community_comments')
    with op.batch_alter_table('community_posts', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_community_posts_user_id'))
        batch_op.drop_index(batch_op.f('ix_community_posts_tool_slug'))
        batch_op.drop_index(batch_op.f('ix_community_posts_created_at'))

    op.drop_table('community_posts')
    # ### end Alembic commands ###
