"""add outreach tables

Revision ID: b7f4257123f2
Revises: 17fcceffef35
Create Date: 2026-07-04 18:06:08.522764

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b7f4257123f2'
down_revision = '17fcceffef35'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('outreach_candidates',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('product_name', sa.String(length=255), nullable=False),
    sa.Column('tagline', sa.String(length=500), nullable=True),
    sa.Column('website_url', sa.String(length=500), nullable=True),
    sa.Column('founder_name', sa.String(length=255), nullable=True),
    sa.Column('email', sa.String(length=255), nullable=True),
    sa.Column('status', sa.String(length=50), nullable=False),
    sa.Column('draft_subject', sa.Text(), nullable=True),
    sa.Column('draft_body', sa.Text(), nullable=True),
    sa.Column('email_source', sa.String(length=100), nullable=True),
    sa.Column('confidence_score', sa.Integer(), nullable=True),
    sa.Column('tone', sa.String(length=20), nullable=False),
    sa.Column('ph_launch_id', sa.String(length=100), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('last_status_change_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('outreach_candidates', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_outreach_candidates_ph_launch_id'), ['ph_launch_id'], unique=True)
        batch_op.create_index(batch_op.f('ix_outreach_candidates_status'), ['status'], unique=False)

    op.create_table('outreach_email_logs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('candidate_id', sa.Integer(), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('subject', sa.String(length=500), nullable=False),
    sa.Column('body', sa.Text(), nullable=False),
    sa.Column('status', sa.String(length=50), nullable=False),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.Column('sent_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['candidate_id'], ['outreach_candidates.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('tools', schema=None) as batch_op:
        batch_op.add_column(sa.Column('academic_integrity_rating', sa.String(length=50), nullable=True))
        batch_op.add_column(sa.Column('academic_warning', sa.Text(), nullable=True))

    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_users_public_username'), ['public_username'], unique=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_users_public_username'))

    with op.batch_alter_table('tools', schema=None) as batch_op:
        batch_op.drop_column('academic_warning')
        batch_op.drop_column('academic_integrity_rating')

    op.drop_table('outreach_email_logs')
    with op.batch_alter_table('outreach_candidates', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_outreach_candidates_status'))
        batch_op.drop_index(batch_op.f('ix_outreach_candidates_ph_launch_id'))

    op.drop_table('outreach_candidates')
    # ### end Alembic commands ###
